name: Sofifa Scraper

on:
  workflow_dispatch:  # Acionamento manual

jobs:
  scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Atualizado para v4

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Atualizado para v4
        with:
          node-version: '20'  # Recomendado usar Node.js 20 (LTS)

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: |
          npm run download-urls
          npm run full

      - name: Upload data to GitHub Actions artifacts
        uses: actions/upload-artifact@v4  # Versão mais recente e estável
        with:
          name: players-data
          path: ./data  # Certifique-se de que este caminho está correto