name: Sofifa Scraper

on:
  workflow_dispatch:

jobs:
  scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'  # Habilita cache de dependências

      - name: Install dependencies (scraping)
        working-directory: ./scraping  # Instala dependências dentro da pasta scraping
        run: npm ci  # Usa npm ci para instalação limpa (recomendado em CI)

      - name: Run scraper
        working-directory: ./scraping  # Executa os comandos dentro da pasta scraping
        run: |
          npm run download-urls
          npm run full

      - name: Upload dados coletados
        uses: actions/upload-artifact@v4
        with:
          name: players-data
          path: data/  # Caminho dos arquivos de saída (na raiz)